[font]
size = 10.0
normal = { family = "Lilex Medium" }
# offset = { x = 1 }

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#222222"
blue = "#6699cc"
cyan = "#6bc1d0"
green = "#99c794"
magenta = "#c594c5"
red = "#ec5f67"
white = "#ffffff"
yellow = "#fac863"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[window]
opacity = 0.9

[window.padding]
x = 20
y = 20
